"""Add profile fields

Revision ID: 36a40d0f3872
Revises: 3f9ca0f94f7b
Create Date: 2025-09-13 11:00:19.675666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a40d0f3872'
down_revision = '3f9ca0f94f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('blood_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('disability')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
