"""Add document_filename to MedicalHistory

Revision ID: f14d0428d29a
Revises: 36a40d0f3872
Create Date: 2025-09-13 11:06:49.018406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14d0428d29a'
down_revision = '36a40d0f3872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_filename', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_column('document_filename')

    # ### end Alembic commands ###
